Feature/directives
StepicOrg/intellij-plugins pull request #2
Opened 2016-10-06 16:00 UTC by 2Pit

- [ ]  @taery
[IDEA-47](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-47)
[IDEA-48](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-48)

1. Добавлена кнопка. Если её нажать текущий код оборачивается в специальные комментарии (директивы).
![pr1](https://cloud.githubusercontent.com/assets/11159462/19159552/981a88e2-8bf5-11e6-849e-e1471b92526e.png)

2. Для Java весь код также заворачивается в класс Main
![pr2](https://cloud.githubusercontent.com/assets/11159462/19159627/db5e8c84-8bf5-11e6-984c-51d1a7eb8f3e.png)

3. Повторное нажатие убирает комментарии и весь внешний код. Если внешнего кода больше чем одна строчка с какой-нибудь стороны, то отображается предупреждение.
![pr3](https://cloud.githubusercontent.com/assets/11159462/19159673/03759424-8bf6-11e6-9d1f-b307e0960b28.png)

4. Во время проверки на платформу отправляется код содержащийся между комментариев.
![pr4](https://cloud.githubusercontent.com/assets/11159462/19160001/febe6220-8bf6-11e6-9471-6b813e0561b8.png)

2016-10-06 18:25 UTC, meanmail commented
А если для этой цели использовать аннотации?

2016-10-06 18:59 UTC, 2Pit commented
@meanmail 
1. С комментариями работать и проще, и понятнее.
2. Хочется иметь универсальное решение для всех языков, а не только для Java и Python.

+ я не знал, что в Python тоже есть аннотации.

2016-10-06 19:06 UTC, meanmail commented
А окружающий код можно полуть по API или только вручную?

2016-10-06 19:19 UTC, 2Pit commented
Получить? Нет, его никак нельзя получить. Я его не отправляю на платформу, соответственно он нигде, кроме компьютера студента, не сохраняется. 
В принципе, можно заворачивать окружающий код в комментарии. Но мне кажется это никому не пригодится.

2016-10-06 19:28 UTC, meanmail commented
Хотелось бы поучаствовать в разработке. Вы это приветствуете? :)

2016-10-06 19:29 UTC, taery commented
@meanmail, приветствуем =)

2016-10-06 19:37 UTC, 2Pit commented
Да, приветствуем) До конца недели допишу мануал по сборке проекта.

2016-10-06 19:39 UTC, meanmail commented
Отлично! Завтра начну изучать код :)

2016-10-06 19:41 UTC, taery commented
@meanmail, если будете делать прямо новую фичу - просьба обсудить со мной сначала идею, чтобы не делать просто так =) Можно путем создания issue [тут](https://github.com/StepicOrg/intellij-plugins/issues)

2016-10-07 09:15 UTC, taery commented
@2Pit я правильно понимаю, что кнопка нужна пока не умеем автоматически понимать, что нужно обернуть код во что-то? Она только для одного шага? - хочется уметь автоматом нажать ее на всем курсе-модуле - иначе это жесть (в джаве же ты ничего не запустишь пока не скомпилируется весь проект)

2016-10-07 09:18 UTC, taery commented
Еще кажется, нужно в комментарии написать побольше, нужно пояснение, что внимание, при сабмите отправится только код, заключенный между комментариями. И написать это нужно и сверху и снизу.

2016-10-07 09:29 UTC, 2Pit commented
Я не думаю, что так стоит писать каждый раз. Достаточно сказать пользователю об этом один раз. Лучше будет завести кнопку "info" с описанием всех фич. Плохо только то, что её можно будет увидеть (как и всю панель) только после загрузки курса.

2016-10-07 09:39 UTC, taery commented
> Я не думаю, что так стоит писать каждый раз. Достаточно сказать пользователю об этом один раз.

Как ты планируешь определять, что ты ему это уже один раз сказал? А если он пришел в плагин через месяц и все забыл? Я уверена на 98%, что стоит такое выкатить, тебя завалят вопросами, а почему я что-то написал в файле, а оно не засабмитилось? Не нужно писать сочинений, думаю по 2 строки будет достаточно, чтобы оно всегда явно выделялось в файле:

```
// Please note, only the code below will be sent to Stepik.org
// Stepik code: begin

тут уже сам код

// Stepik code: end
// Please note, only the code above will be sent to Stepik.org
```
"info" - идея классная, но я вот например никогда не читаю описание фич, в идеале фичи должны быть self-discoverable =)

2016-10-07 09:40 UTC, meanmail commented
Сейчас как раз помогаю ученикам по курсу Java. Делаю обертки к задачам и тесты, чтобы можно было тестировать код методов. Так дело в том, что много задач в которых обернуть в класс Main недостаточно, нужно ещё добавлять абстрактные классы, классы исключений, перечисления, кучу кода для проверки одного единственного метода.

2016-10-07 10:08 UTC, 2Pit commented
> Как ты планируешь определять, что ты ему это уже один раз сказал?

Этого я не смогу понять, а если и скажу то вряд ли пользователь прочитает)
Ок. Сделаю по-твоему. В будущем, возможно, при повторной вставке директив не буду показывать описание директив. 

> нужно ещё добавлять абстрактные классы, классы исключений, перечисления

После того как шаблон обернётся в Main. Несуществующие классы удобно импортировать через ctrl + Enter или брать их из описания задачи. Автоматически анализировать текст задачи и вставлять оттуда куски кода правильно очень сложно, проще перенести эту нагрузку на пользователя. Ведь класс может быть внутренним, внешним, какой-нибудь произвольной глубины вложенности.

2016-10-07 10:11 UTC, taery commented
> нужно ещё добавлять абстрактные классы, классы исключений, перечисления

В любом случае это не в рамках текущей задачи.

2016-10-07 10:22 UTC, taery requested changes

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static String getTextUnderDirectives(VirtualFile vf, SupportedLanguages lang){
@2Pit, давай начнем по-немногу тесты писать. Кажется, этот метод, хороший кандидат. Равно как и остальные методы тут.

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        return line.equals("Stepik code: start");
Такие строки лучше вынести в константы.  И "главное правило equals": вызывать его всегда лучше на том, что точно не `null`.

т.е. `"some text".equals(variable)`

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        return line.equals("Stepik code: end");
Тут тоже

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static SupportedLanguages loadLangSettings(String lang) {
Этот метод кажется стоит двинуть прямо в enum

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        int start = locations.first == null ? 0 : locations.first;
А ты не хочешь не делать пары с null-ами и унести эту логику в вычисление позиций?

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        for (int i = start + 1; i < end; i++) {
точно ли тут всегда start+1? а если директив не было, позиция будет с 0 и ты тогда самую первую строчку пропустишь, это ок или так задумано(я вот подумала сейчас, это не package случайно так обрезается?)?

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        String[] text = document.getText().split("\n");
Получается, ты дважды вытаскиваешь документ, сплитишь в нем текст. Кажется, лучше вынести эту логику в отдельный метод и вызвать его один раз, а сюда передавать уже массив строк.

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    //    Find first "start" and last "end". If it was not find, method return null;
Такого рода комментарии лучше делать в стиле java-doc, хотя от логики с null я бы лучше избавилась. И самое главное, тут ведь написана не совсем правда, ты же не вернешь `null`, ты вернешь `Pair(null, null)`.

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static Pair<Integer, Integer> findDirectives(VirtualFile vf, SupportedLanguages lang) {
Все эти методы стоит потестировать: а что будет, если есть только начальная директива(ну удалили случайно остальное)? если только конечная? что если встретилась сначала конечная, потом начальная?

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        return Pair.create(start, end);
Возможно, стоит возвращать вообще не пару. Может там должен быть объект, с началом, концом и текстом в промежутке?

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +        return new String[]{SHORTCUT};
я не очень знаю как там все внутри устроено, если так сделать, переопределить шорткат возможно?

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +import com.jetbrains.tmp.learning.LangSetting;
Что за название класса, мы его можем переименовать? о.О

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/SwitchLanguage.java
> +            secondLang = SupportedLanguages.PYTHON;
такие ифы лучше с фигурными скобками делать.

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/SwitchLanguage.java
> +        final PsiFile second = PsiManager.getInstance(project).findFile(hide.getVirtualFile().findChild(secondLang.getMainFileName()));
больно уже длинная строка, давай переносы.

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/StepikJavaPostAction.java
> +                            while (ans.equals("evaluation") && count < 200) {
опять, правило `equals` ;-)  и что за магические константы?

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/StepikJavaPostAction.java
> +                StepikWrappers.SubmissionToPostWrapper sTPW = new StepikWrappers.SubmissionToPostWrapper(attemptId, currentLang, solution);
`sTPW` - не надо так называть переменные.

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +        if (locations.first == null && locations.second == null) {
Я правильно понимаю, что общий смысл вот этого всего, что ты если первый раз нажал на кнопку - директивы вставились, второй раз - удалились?

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +        String text[] = document.getText().split("\n");
И опять разбор всего текста снова =)

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +                        () -> document.setText(sb.toString())), "Remove Stepik directives", "Remove Stepik directives");
Выноси повторяющиеся тексты в константы.

2016-10-07 10:22 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +        String text[] = document.getText().split("\n");
И четвертый раз разбор файла. =)

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static String getTextUnderDirectives(VirtualFile vf, SupportedLanguages lang){
Написал тесты на этот метод

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        int start = locations.first == null ? 0 : locations.first;
Исправил

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        for (int i = start + 1; i < end; i++) {
Тут была ошибка. Теперь если директивы start нет, то start = -1

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    //    Find first "start" and last "end". If it was not find, method return null;
Исправил

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static Pair<Integer, Integer> findDirectives(VirtualFile vf, SupportedLanguages lang) {
Если одной из директив нет, то всё хорошо работает. 
Если они перепутаны, то пользователь сам виноват) Это же программирование - нельзя всё за ними исправлять)

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static Pair<Integer, Integer> findDirectives(VirtualFile vf, SupportedLanguages lang) {
Хотя ты права, я такой случай не проверял. Мало ли какая ошибка выскочит

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        String[] text = document.getText().split("\n");
Отрефакторил. Теперь все эти методы в DirectiveUtils

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +import com.jetbrains.tmp.learning.LangSetting;
Не спорю, название так себе. А как бы ты его назвала? Класс вставляет и удаляет директивы.

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +        if (locations.first == null && locations.second == null) {
Ага

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        return line.equals("Stepik code: start");
fixed

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        return line.equals("Stepik code: end");
fixed

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +        return new String[]{SHORTCUT};
Как это "так"? И я не понимаю зачем.
С шорткатами проблема - они не работают. И я не понимаю почему.

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        return Pair.create(start, end);
Не. В таком случае получается метод **getTextUnderDirectives**, а мне **findDirectives** ещё как минимум в одном месте нужен.

2016-10-11 14:39 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/StepikJavaPostAction.java
> +                            while (ans.equals("evaluation") && count < 200) {
Здесь константы -- это таймер. Я потом хочу весь метод переписать.

2016-10-12 09:00 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/StepikJavaPostAction.java
> +                            while (ans.equals("evaluation") && count < 200) {
Даже если хочешь переписать - все равно лучше сразу писать так, чтобы было понятно, что происходит. Лучше делать именованные константы в таких случаях

2016-10-12 09:04 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        return Pair.create(start, end);
ок, пусть пока так будет.

2016-10-12 09:06 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static String[] removeDirectives(String[] text, Pair<Integer, Integer> locations,boolean showHint, Project project) {
`CTRL+ALT+L`

2016-10-12 09:07 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        final int k = showHint ? 2 : 1;
Вот эта логика конечно жесть..

2016-10-12 09:13 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +        return new String[]{SHORTCUT};
=) ну я не знаю как они работают, потому и спрашиваю.

2016-10-12 09:14 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        else {
А у тебя при автоформате идея `else` на новой строке оставляет?

2016-10-12 09:15 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/StepikJavaPostAction.java
> +                            while ("evaluation".equals(ans) && count < FIVE_MINUTES) {
👍

2016-10-12 09:16 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static String[] removeDirectives(String[] text, Pair<Integer, Integer> locations,boolean showHint, Project project) {
тебе пробел перед boolean не нравится или то что строка длинная ?

2016-10-12 09:17 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        else {
нет. Просто я ядре такой синтаксис. И я иногда путаю где я нахожусь. Исправлю

2016-10-12 09:18 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/SwitchLanguage.java
> +        if (currentLang.getName().equals("java8")) {
а не хочешь сделать опять же енаму метод `isJava8()?` А зачем нужен вообще secondLang?

2016-10-12 09:20 UTC, taery commented on stepik-union/test/org/stepik/plugin/actions/DirectivesUtilsTest.java
> +        fileName = "test/org/stepik/plugin/actions/text/samples/" + fileName;
😱

2016-10-12 09:23 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/SwitchLanguage.java
> +        if (currentLang.getName().equals("java8")) {
Здесь надо придумать что-нибудь по умнее. В этом методе меняется язык степа с текущего на второй (правильнее назвать newLang) , пока только 2 языка хватает и if-а

2016-10-12 09:23 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    public static String[] removeDirectives(String[] text, Pair<Integer, Integer> locations,boolean showHint, Project project) {
Пробел, хотя строчка тоже длинновата. Я обычно как критерий использую просмотр в гитхабе, если снизу есть полоса прокрутки - то надо бы покороче. У тебя она есть =)

2016-10-12 09:26 UTC, 2Pit commented on stepik-union/test/org/stepik/plugin/actions/DirectivesUtilsTest.java
> +        fileName = "test/org/stepik/plugin/actions/text/samples/" + fileName;
А как правильно?

2016-10-12 09:26 UTC, taery commented on stepik-union/test/org/stepik/plugin/actions/DirectivesUtilsTest.java
> +        fileName = "test/org/stepik/plugin/actions/text/samples/" + fileName;
Во, нашла. `this.getClass().getResource()`. Пожалуюсь Леше, что ты из его курса самое важное не увидел =)

2016-10-12 09:26 UTC, 2Pit commented on stepik-union/test/org/stepik/plugin/actions/DirectivesUtilsTest.java
> +        fileName = "test/org/stepik/plugin/actions/text/samples/" + fileName;
Там ещё в след строке вызывается абсолютный путь

2016-10-12 09:29 UTC, taery commented on stepik-union/test/org/stepik/plugin/actions/DirectivesUtilsTest.java
> +        fileName = "test/org/stepik/plugin/actions/text/samples/" + fileName;
Дада, я видела. зачем?
На самом деле, еще лучше можно и нужно `new Scanner(this.getClass().getResourceAsStream("имя файла"))`

2016-10-12 09:30 UTC, taery commented on stepik-union/test/org/stepik/plugin/actions/DirectivesUtilsTest.java
> +            System.out.println("python test " + i + " passed");
^_^ вот это забавно, это для лучшего логирования результата теста?

2016-10-12 09:31 UTC, taery commented on stepik-union/test/org/stepik/plugin/actions/DirectivesUtilsTest.java
> +        fileName = "test/org/stepik/plugin/actions/text/samples/" + fileName;
А, я поняла, у тебя структура неправильная, потому не работает видимо. Ща я себе выгружу посмотрю.

2016-10-12 11:12 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        final int k = showHint ? 2 : 1;
Не могу придумать ничего лучше

2016-10-12 11:14 UTC, taery approved these changes

2016-10-12 11:25 UTC, merged