Reset task action work now and supported undo action
StepicOrg/intellij-plugins pull request #20
Opened 2016-10-23 14:44 UTC by meanmail

- [ ] @taery 
- [ ] @2Pit 

Исправлен не работающий **Reset Task Action**.
Этот action - копипаста **StudyRefreshTaskFileAction.** Просто унаследоваться от него невозможно. Методы, которые нужно переопределить - статические. А те, что не нужно менять приватные, вот и получается, что от наследования никакого смысла. Но так как ядро пока что менять нельзя, поэтому сделал так.

Что нового:
- Теперь этот action работает с курсами с courseMode == "stepik_code"
- Этот action поддерживает Undo

2016-10-24 12:23 UTC, taery requested changes

2016-10-24 12:23 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
> +                .getInstance()
кажется, первый вызов в стиле "билдеры" лучше не переносить на отдельную строчку, а то сам изначальный класс "выпадает". Не знаю, на сколько понятно обяснила

2016-10-24 12:23 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
> +                JBPopupFactory.getInstance().createHtmlTextBalloonBuilder(text, messageType, null);
и вот тут, равно в никуда тоже выглядит не очень. Кажется, лучше так:
```
BalloonBuilder balloonBuilder = JBPopupFactory.getInstance()
              .createHtmlTextBalloonBuilder(text, messageType, null);
```

2016-10-24 12:23 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
> +                JBPopupFactory.getInstance().createHtmlTextBalloonBuilder(text, messageType, null);
ну только отступ я от балды сделала - идея правильно отформатирует.

2016-10-24 12:23 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
> +                                .runWriteAction(
получается не очень читабельно. Может лучше если открывающая скобка на отдельной строке - то закрывающую тоже на отдельную вынести, чтобы было понятно, где все заканчивается.

2016-10-24 12:23 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
> +                    .getExtensions(StudyActionListener.EP_NAME)) {
Тут точно в длину строки не влезает?

2016-10-24 12:23 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
> +        super("Reset Task File (" + KeymapUtil.getShortcutText(new KeyboardShortcut(KeyStroke.getKeyStroke(SHORTCUT), null)) + ")", "Refresh current task",
Не смотря на все сокращения строк одно место таки не влезло =)

2016-10-24 12:23 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
> +        if (!(EduNames.STEPIK_CODE.equals(courseMode)||
Тут тоже, кажется, что если в длину строки помещается, лучше не разбивать ифы и форы на разные строки.

2016-10-24 12:23 UTC, taery commented on stepik-union/src/main/resources/META-INF/plugin.xml
> +        <applicationConfigurable
Для xml даже не знаю, давайте тоже обсудим стиль. Кажется, что тут влезание в длину строки выглядит не очень =(

2016-10-24 15:13 UTC, meanmail commented on stepik-union/src/main/resources/META-INF/plugin.xml
> +        <applicationConfigurable
@taery даже не знаю как лучше для xml, там ну очень длинные строки, но с переносами читается плохо, каша из тегов какая-то получается.

2016-10-24 15:16 UTC, taery commented on stepik-union/src/main/resources/META-INF/plugin.xml
> +        <applicationConfigurable
Ну вот и мне кажется, что для конфигов, которые не часто редактируются лучше делать длинные читабельные строки, чем так переносить

2016-10-24 15:30 UTC, meanmail commented on stepik-union/src/main/resources/META-INF/plugin.xml
> +        <applicationConfigurable
Согласен

2016-10-26 11:11 UTC, taery approved these changes

2016-10-26 12:16 UTC, merged