Feature/improve metrics
StepicOrg/intellij-plugins pull request #33
Opened 2016-11-03 16:17 UTC by 2Pit

- [ ]  @taery 
- [ ] @meanmail 

[IDEA-36](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-36)
Метрики создаются через MetricBuilder.
В метрики добавлен тег **language**.
Теперь неиформативные поля отсутствуют.
Например тег **lang:java8**  и тег **action:get_course** одновременно не встречаются. 
Также **action:get_course** и **data:step_id**

2016-11-03 19:40 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +    }
Добавить приватный конструктор, раз у нас фабрика

2016-11-03 19:40 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +        if (!MetricActions.GET_COURSE.toString().equals(action) && isAnyNull(courseId, stepId, language)) {
Повторяющийся код
Может что-нибудь такое?
`boolean isGetCourseAction = MetricActions.GET_COURSE.toString().equals(action);`
`if (isGetCourseAction) {`
`    return (courseId != null ...`
`} else {`
`    return !isAnyNull(...`
`}`

2016-11-03 19:40 UTC, meanmail commented on core/src/test/java/com/jetbrains/tmp/learning/stepik/MetricBuilderTest.java
> +    public void check1() {
Названия тест-методов должны быть говорящими о том что они проверяют

2016-11-03 19:40 UTC, meanmail commented on core/src/test/java/com/jetbrains/tmp/learning/stepik/MetricBuilderTest.java
> +    public void checkInvalidPost() {
Одна проверка на один метод

2016-11-03 19:40 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/from/edu/intellij/utils/generation/StepikProjectGenerator.java
> +
Закомментированный код - это как бы плохой стиль, его надо избегать. Идея конечно отслеживает зависимости и в этом коде, но он может стать устаревшим и потом не разберешь что он делает правильно, а что нет. Лучше параллельную ветку в git.

2016-11-03 19:40 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/actions/DownloadSubmission.java
> +
Лишняя пустая строка

2016-11-04 03:53 UTC, meanmail commented
Дело вкуса наверное, но я вот не очень хорошо отношусь к использованию внутренних классов из вне: названия классов в определении переменных/параметров очень длинные. Лучше отдельный пакет и туда всё поместить отдельными классами. Удобочитаемость страдает как по мне.

2016-11-04 10:39 UTC, taery requested changes

2016-11-04 10:39 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +    public static class MetricsWrapper {
Не-не-не. Зачем все писать в один файл? =(

2016-11-04 10:39 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +        private MetricsWrapper(
В крайнем случае, только если очень надо.

2016-11-04 10:46 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +    public static class MetricsWrapper {
Не, я это переделаю. Создам директорию и раскидаю по файлам. Просто по инерции от StepikWrapper осталось.

2016-11-04 10:54 UTC, taery requested changes

2016-11-04 10:54 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +        return new MetricBuilder();
А зачем, собственно так? почему не просто конструктор?

2016-11-04 10:54 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +    private static boolean isAnyNull(Object... objects) {
Еще, каждый раз, когда пишешь такие методы, стоит задуматься, нет ли что-то реализованного уже. У нас теперь есть хорошая сборка, можно легко подключать зависимости. К сожалению, прям сходу пример не вспомню - но попробуй поизучать что есть в google guava и apache commons, наверняка там будет что-то полезное и уже реализованное.

2016-11-04 10:54 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +    private static boolean isAnyNull(Object... objects) {
В целом, кажется, что билдер должен выглядеть как-то не так, стоит еще подумать.

2016-11-04 10:54 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +    private static boolean isAnyNull(Object... objects) {
Можешь описать словами, что ты хочешь чтобы он делал?

2016-11-07 13:49 UTC, 2Pit commented
- убрал getInstance() теперь только new MetricBuilder()
- разделил MetricBuilder на несколько файлов
- исправил тесты (названия + каждая проверка в отдельном тесте)

2016-11-07 15:47 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +    private static boolean isAnyNull(Object... objects) {
в google guava, пока что ничего такого не нашёл.
Я хочу чтобы Builder создавал метрики, и проверял правильную ли метрику мы создали.

2016-11-08 08:18 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +    }
Исправил. Теперь getInstance() не будет

2016-11-08 08:19 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/MetricBuilder.java
> +        if (!MetricActions.GET_COURSE.toString().equals(action) && isAnyNull(courseId, stepId, language)) {
вынес только флаг isGetCourseAction
чтобы код было читать удобнее

2016-11-08 08:19 UTC, 2Pit commented on core/src/test/java/com/jetbrains/tmp/learning/stepik/MetricBuilderTest.java
> +    public void check1() {
Исправил

2016-11-08 08:23 UTC, 2Pit commented on stepik-union/src/main/java/org/stepik/from/edu/intellij/utils/generation/StepikProjectGenerator.java
> +
Залил в параллельную ветку. Просто мне этот код должен понадобится в ближайшее время.

2016-11-08 13:01 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +    private Integer stepId = null;
Ведь и так будет инициализированно в null

2016-11-08 13:01 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +        this.name = name.toString();
Почему toString(), а не геттер? Здесь и MetricAction, SupportedLanguages и т.д.

2016-11-08 13:01 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +            return new MetricsWrapper(EduNames.INVALID, null, null, null, null, null);
Может сделать константный объект INVALID_METRICS_WRAPPER и его возвращать, а не плодить кучу одинаковых объектов?

2016-11-08 13:01 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +        boolean isGetCourseAction = MetricActions.GET_COURSE.toString().equals(action);
Может лучше сравнение перенести внутрь enum'а, добавить метод который принимает строку и внутри сравнивает имя и action

2016-11-08 13:01 UTC, meanmail commented on core/src/test/java/com/jetbrains/tmp/learning/stepik/MetricBuilderTest.java
> +        if (inputStream == null) return null;
Мне кажется лучше исключение бросить, а то может случится ложно-отрицательный результат теста. Например, тестируемый метод вернет null и здесь null, а на самом деле и тестируемый код и сам тест неправильно работают.

2016-11-08 13:45 UTC, meanmail commented
Ещё проставить NotNull/Nullable где нужно

2016-11-08 15:45 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +        this.name = name.toString();
Теперь использую 
`this.name = name.getTag();`

2016-11-08 15:46 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +        boolean isGetCourseAction = MetricActions.GET_COURSE.toString().equals(action);
не думаю, что ради одного раза стоит так делать

2016-11-08 15:46 UTC, 2Pit commented on core/src/test/java/com/jetbrains/tmp/learning/stepik/MetricBuilderTest.java
> +        if (inputStream == null) return null;
исправил

2016-11-11 15:59 UTC, taery requested changes

2016-11-11 15:59 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +    public MetricBuilder addTag(PluginNames name) {
Может лучше называть методы не абстрактно, а ровно так, как называется параметр? `addName`?

2016-11-11 15:59 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +            return new MetricsWrapper(EduNames.METRIC_NAME, name, action, language, courseId, stepId);
зачем передавать много параметров в конструктор, когда можно передать сам объект?

2016-11-11 15:59 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +            return new MetricsWrapper(EduNames.METRIC_NAME, name, action, language, courseId, stepId);
И вообще, в самом MetricsWrapper можно спрятать эту логику.

2016-11-11 15:59 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
а ты умеешь сюда передать просто null?

2016-11-11 15:59 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricsWrapper.java
> +            String metricName) {
А решили чтоли так делать по код стайлу? Дружно пишете новую строку после открывающей скобки. Это же не очень смотрится, как мне кажется.

2016-11-11 15:59 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricsWrapper.java
> +        class Data {
Опять вложенные классы. Они снаружи нигде не используются?

2016-11-11 16:48 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
Оказывается можно
![snapshot3](https://cloud.githubusercontent.com/assets/10301297/20222813/55e6fbaa-a869-11e6-9dde-801c546f5e0e.png)

2016-11-11 16:49 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
Варнинги конечно сыплются и то потому, что небезопасный cast, а так компилятор вполне доволен :)

2016-11-11 16:54 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
Больше того! Можно вообще запустить без параметров и тогда поведение интересное, не такое как с **null**

2016-11-11 16:55 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
C varargs нужно быть осторожнее оказывается

2016-11-11 16:56 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricsWrapper.java
> +            String metricName) {
Это в код стайле :)

2016-11-11 17:03 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricsWrapper.java
> +        class Data {
Это для сериализации, так что норм :)

2016-11-11 17:03 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
Не-не. Ничего не можно =) Ты только показал, что у тебя метод вернул true ;-) Попробуй напечатать сам objects.

2016-11-11 17:04 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
Я, если честно, не знаю - что там будет, но что-то мне подсказывает, что objects не должен быть null-ом ни при каких обстоятельствах.

2016-11-11 17:05 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
А какие могут быть варнинги, знаешь, что по сути варарги?

2016-11-11 17:07 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
А без параметров false вернет, как я полагаю.

2016-11-11 17:07 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
Но вообще да, варарги надо использовать только в случае очень уж необходимости.

2016-11-11 17:07 UTC, meanmail commented
Ещё нужно у всех классов/полей/методов сделать минимально необходимый модификатор доступа

2016-11-14 16:21 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
Добавил аннотацию NotNull

2016-11-14 16:22 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricUtils.java
> +        if (objects == null) return true;
Без параметров, получается пустой массив, null-ов нету значит false

2016-11-14 17:46 UTC, meanmail requested changes

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/SupportedLanguages.java
> +    public String getTag() {
Есть же getName(). Этот класс ничего не должен знать ни о метриках и ни о тегах.

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricActions.java
> +    public String getTag() {
Это же по сути тоже getName()?

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +    public MetricBuilder addTagName(PluginNames name) {
1) Тут же не add, а set. А то кажется будто если два раза вызвать addTagName, то добавится два тега.
2) Имя у параметра всё-таки лучше pluginName, а еще лучше если само перечисление будет называться Plugins. Тогда логичнее выглядит конструкция plugin.getName(), например.
3) Сам метод назвать setPlugin(...), текущее название не говорит о том что делает метод.

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +    public MetricBuilder addTagAction(MetricActions action) {
Тоже что и для addTagName

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +    public MetricBuilder addTagLanguage(SupportedLanguages language) {
Тоже что и для addTagName

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +    Integer stepId;
Поля наружу, нехорошо, как же инкапсуляция? Всё же поля лучше использовать через геттеры

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +        this.name = name.getTag();
NPE

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +        this.action = action.getTag();
NPE

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricBuilder.java
> +        this.language = language.getTag();
NPE

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricsWrapper.java
> +    MetricsWrapper(MetricBuilder metricBuilder) {
NotNull

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricsWrapper.java
> +            this.name = mb.metricName;
NPE

2016-11-14 17:46 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/PluginNames.java
> +    public String getTag() {
getName()
Этот класс также не должен знать о том что происходит вне его, ни о каких метриках и тегах.

2016-11-14 17:46 UTC, meanmail commented on core/src/test/java/com/jetbrains/tmp/learning/stepik/MetricBuilderTest.java
> +}
Нет проверок, для случаев:
.addTagAction(null)
.addTagName(null)
.addTagLanguage(null)
Но если проставить в соответствующих классов NotNull, то эти проверки не нужны

2016-11-14 18:04 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikJavaPostAction.java
> +                    MetricsWrapper metric = new MetricBuilder().addTagName(PluginNames.STEPIK_UNION)
Мне кажется имя плагина должно задаваться только в одном месте в gradle (productFlavors).

2016-11-14 18:55 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricActions.java
> +    public String getTag() {
В отличии от SupportedLanguage эти классы создавались именно для того чтобы хранить теги.

2016-11-14 18:57 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/SupportedLanguages.java
> +    public String getTag() {
Ок. Тут исправлю

2016-11-14 18:58 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/metric/MetricActions.java
> +    public String getTag() {
Можно переименовать методы, но не вижу большого смысла)

2016-11-14 19:31 UTC, 2Pit commented
@meanmail @taery 
Я перепишу метрики

2016-11-14 19:38 UTC, closed without merging