Add sandbox module
StepicOrg/intellij-plugins pull request #36
Opened 2016-11-15 10:55 UTC by 2Pit

- [ ]  @taery 
- [ ]  @meanmail 

Вместо модуля Util создается модуль Sandbox
![image](https://cloud.githubusercontent.com/assets/11159462/20303114/f826f306-ab3a-11e6-83fe-16cb61159415.png)

решено [IDEA-39](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-39)
частично [IDEA-56](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-56)

2016-11-15 10:59 UTC, 2Pit commented
Пока тестировал плагин к релизу, понял что не хватает Sandbox.
Добавление модуля естественное продолжение  [PR-32 Safe move and rename dirs](https://github.com/StepicOrg/intellij-plugins/pull/34)

Решил также почистить код от использования utilModule т.к. по назначению он не используется и пока непонятно когда использоваться будет.

2016-11-15 15:42 UTC, meanmail requested changes

2016-11-15 15:42 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaTaskBuilder.java
>          String moduleName = name + "-" + taskName;
Давно хотел спросить, а почему такое название модуля, а не просто taskName?

2016-11-15 15:42 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaTaskBuilder.java
>              return module;
Лишний **return**

2016-11-15 15:42 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaTaskBuilder.java
>      private static final String SRC = "src";
Заменить на **EduNames.SRC**

2016-11-15 15:42 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaSectionBuilder.java
> +    StepikJavaSectionBuilder(@NotNull String moduleDir, Section section) {
Для section NotNull

2016-11-15 15:42 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/JavaCourseBuilder.java
>          }
Для всех параметров этого метода проставить NotNull

2016-11-15 15:42 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/JavaCourseBuilder.java
> +    public void createLessonModules(@NotNull ModifiableModuleModel moduleModel,
Тоже NotNull'ы проставить и ниже для метода **setupRootModel**

2016-11-15 15:42 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/from/edu/intellij/utils/generation/builders/CourseBuilder.java
>              throws InvalidDataException, IOException, ModuleWithNameAlreadyExists, JDOMException, ConfigurationException;
NotNull для параметров здесь и у класса, реализующего данный интерфейс

2016-11-15 15:44 UTC, meanmail commented
stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaTaskBuilder.java 
#118 Paths.get(FileUtil.join(...
FileUtil.join - лишний, Paths.get сам умеет join

2016-11-15 16:15 UTC, 2Pit commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaTaskBuilder.java
> -        ModuleRootModificationUtil.addDependency(module, myUtilModule);
Может быть из-за этого

2016-11-15 16:15 UTC, 2Pit commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaTaskBuilder.java
>          String moduleName = name + "-" + taskName;
https://github.com/StepicOrg/intellij-plugins/pull/36/commits/d13f2350eb4214abce3ea630a36835ca51aa2bcf#r88051730

2016-11-15 16:26 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaTaskBuilder.java
>          String moduleName = name + "-" + taskName;
То есть как я понимаю, это было сделано так как разные таски могут иметь одинаковые имена, то возможно это сделано для уникальности имен модулей и теперь это не нужно, раз нет модуля **util**

2016-11-15 16:39 UTC, meanmail commented
Исправь, пожалуйста, мою ошибку, которую я добавил.
В класс **StepikJavaLessonBuilder** нужно добавить метод **getSourcePaths**, который возвращает всегда **null**. Это для того чтобы в директории lesson не создавалась директория **src**.

2016-11-16 10:30 UTC, 2Pit commented on stepik-union/src/main/java/org/stepik/plugin/java/project/wizard/StepikJavaTaskBuilder.java
>          String moduleName = name + "-" + taskName;
Да, можно. Но тут надо много чего исправлять) Нужно будет сделать масштабируемую систему, чтобы легко добавлять поддержку новых степов.

2016-11-16 10:57 UTC, merged