Compatibility with JB Repozitory
StepicOrg/intellij-plugins pull request #4
Opened 2016-10-13 16:19 UTC by 2Pit

- [ ] @taery 

remove: idea-junit and edu-intellij dependency
fix: some shortcuts

2016-10-13 20:31 UTC, taery commented
@2Pit если есть под это задача - пиши ее номер в описании PR, если нет - то создай и пиши  =)

2016-10-13 20:36 UTC, taery requested changes

2016-10-13 20:36 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DownloadSubmission.java
> +        super("Download submission(" + KeymapUtil.getShortcutText(new KeyboardShortcut(KeyStroke.getKeyStroke(SHORTCUT), null)) + ")",
длинновато

2016-10-13 20:36 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DownloadSubmission.java
> +    private static final String ACTION_ID = "STEPIK.DownloadSubmission";
А зачем степик капсом?

2016-10-13 20:36 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DownloadSubmission.java
> +                        () -> documentManager.getDocument(vf).setText(finalCode)), "Download last submission", "Download last submission");
это идея автоформатом развернула лямбду или чего она опять в одну строчку стала?

2016-10-14 05:04 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/StepikJavaPostAction.java
> +        return "STEPIK.StepikJavaPostAction";
Добавить:
`public static final String ACTION_ID = "STEPIC.StepikJavaPostAction";`
Заменить:
`return "STEPIK.StepikJavaPostAction";`
На:
`return ACTION_ID;`

2016-10-14 08:47 UTC, taery commented on .idea/modules/intellij-plugins.iml
> +    <orderEntry type="jdk" jdkName="IntelliJ IDEA Community Edition IC-162.2032.8" jdkType="IDEA JDK" />
а напомни еще , зачем ты сменил вот это? так у меня проект не откроется =(

2016-10-14 08:49 UTC, taery commented on stepik-union/resources/META-INF/plugin.xml
> +        <action id="STEPIK.StepikJavaPostAction" class="org.stepik.plugin.actions.StepikJavaPostAction"/>
А тут не поиспользовать константы, которые у тебя уже есть?

2016-10-14 13:54 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DownloadSubmission.java
> +    private static final String ACTION_ID = "STEPIK.DownloadSubmission";
Чтобы легче находить) Мали что ещё с айдишниками случится.
Я их в следующем PR буду менять. Чтобы они были понятнее

2016-10-14 14:03 UTC, 2Pit commented on stepik-union/resources/META-INF/plugin.xml
> +        <action id="STEPIK.StepikJavaPostAction" class="org.stepik.plugin.actions.StepikJavaPostAction"/>
А их тут никак не получить

2016-10-14 14:16 UTC, meanmail commented on .idea/modules/intellij-plugins.iml
> +    <orderEntry type="jdk" jdkName="IntelliJ IDEA Community Edition IC-162.2032.8" jdkType="IDEA JDK" />
Я из своей ветки убрал каталог .idea и добавил его .git/info/exlude. Конфиги хранятся только локально и не отправляются в гитхаб. Нет потом конфликтов. Пока так не сделал приходилось после каждого чекаута настраивать либы и sdk заново.

2016-10-14 14:22 UTC, taery approved these changes

2016-10-14 14:23 UTC, 2Pit commented on .idea/modules/intellij-plugins.iml
> +    <orderEntry type="jdk" jdkName="IntelliJ IDEA Community Edition IC-162.2032.8" jdkType="IDEA JDK" />
Мне кажется, что неправильные имена лучше чем никакие. Сложно пометить все директории если ты его открываешь в первый раз, проще в одном месте сменить project SDK. Но когда перейдём на Gradle проблема решится сама собой.

2016-10-14 14:45 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DownloadSubmission.java
> +                        + KeymapUtil.getShortcutText(new KeyboardShortcut(KeyStroke.getKeyStroke(SHORTCUT), null))
Может быть добавить утилитный метод getShortcutText(SHORTCUT)?

2016-10-14 14:45 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DownloadSubmission.java
> +                "Download last submission");
Текст выделить в константу

2016-10-14 15:07 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DownloadSubmission.java
> +                "Download last submission");
Если все строки буду выносить в константы то быстро в них запутаюсь.

2016-10-14 15:07 UTC, 2Pit commented on stepik-union/src/org/stepik/plugin/actions/DownloadSubmission.java
> +                        + KeymapUtil.getShortcutText(new KeyboardShortcut(KeyStroke.getKeyStroke(SHORTCUT), null))
Пока не стоит, это копипаст из ядра. Пусть будет выглядеть одинаково.

2016-10-14 15:07 UTC, merged