Feature/fix timelimits
StepicOrg/intellij-plugins pull request #43
Opened 2016-11-30 12:47 UTC by 2Pit

- [ ] @taery 
- [ ] @meanmail 

1. Исправлено отображение **time /memory limit** [IDEA-33](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-33)
- Информация о языках и time limits инкапсулирована в Task.
- LangManager - удалён. Переход на новую версию StudyTaskManager.
- Добавлена проверка языка задачи

2. **task.html** - не создаётся вообще, **Main.java, main.py** не создаются в кэше.

2016-11-30 17:36 UTC, taery requested changes

2016-11-30 17:36 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/StudySerializationUtils.java
> +                            e.printStackTrace();
не надо так делать, хотя бы в лог пиши.

2016-12-01 18:31 UTC, taery approved these changes

2016-12-01 19:34 UTC, meanmail requested changes

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudyBasePluginConfigurator.java
> +                String text = StudyUtils.getTaskTextFromTask(taskDirectory, task, project);
Надо бы сигнатуру у метода поменять (project, task, taskDirectory)

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudySerializationUtils.java
> +
Лишняя строчка

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudySerializationUtils.java
> +                            currentLang = getChildWithName(langSetting, "currentLang").getValue();
Новый метод `getOptionalChild(langSetting, "currentLang")` который не выбрасывает исключение, а возвращает null решит эту проблему

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudySerializationUtils.java
> +
Ещё одна

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudySerializationUtils.java
> +                        LangSetting ls = new LangSetting(currentLang, taskLangs);
Никаких зависимостей от других классов, иначе этот класс останется с нами навечно вместе с миграцией :)
А то потом ещё миграцию миграции делать)
То есть здесь используем только классы из стандартных библиотек

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudyTaskManager.java
> +
Пустая строка

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudyTaskManager.java
> +                    //state = StudySerializationUtils.Xml.convertToSixVersion(state, myProject);
Sixth

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudyUtils.java
> +            Project project) {
NotNull?

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudyUtils.java
> +            return getTextWithStepLink(task, project);
Тоже сигнатуру поменять, project вначале

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudyUtils.java
> +            return getTaskTextFromTask(task.getTaskDir(project), task, project);
И тут

2016-12-01 19:34 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/Task.java
> +    private String currentLang = "";
У наж же есть SupportedLanguages может его сюда и прикрутить, а то у нас паралелльно и текст и enum сосуществует

2016-12-01 19:34 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/actions/ActionUtils.java
> +            logger.warn("Can't find SRC vf");
В логах надо пути приписывать и какие-то нужныжные данные, а то у нас логи не информативные

2016-12-01 19:34 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
>          StudyUtils.deleteGuardedBlocks(document);
О, это уже не надо, осталось от placeholderor'ов

2016-12-01 19:34 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/actions/StepikRefreshTaskFileAction.java
> +                        .runWriteAction(() -> document.setText(taskFile.text)),
У нас поле наружу, надо бы геттер

2016-12-01 19:34 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/actions/SwitchLanguage.java
> +        if (srcPsi == null) {
Я застрял на этом моменте никак не мог увидеть разницы :)

2016-12-02 14:14 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/Task.java
> +    private String currentLang = "";
Я пытался, были проблемы с сериализацией. Попробую ещё раз.
А как тебе идя на json перейти?

2016-12-02 14:39 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/Task.java
> +    private String currentLang = "";
Я за, всё равно его используем и будем использовать, пусть только он и будет

2016-12-03 13:01 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/StudySerializationUtils.java
> +        }
Наоборот, код из `getChildWithName(element, name)` вставить сюда, только вместо исключения возвращать null. А вот в сам `getChildWithName` вызывать `getChildWithNameOrNull` и бросать исключение если null. А так сначало бросаем исключение, а потом его же и ловим :)

2016-12-03 13:01 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/Task.java
>      private Map<String, String> timeLimits = new HashMap<>();
А тут в качестве ключа нельзя использовать SupportedLanguages?

2016-12-05 13:51 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/Task.java
>      private Map<String, String> timeLimits = new HashMap<>();
Так и планировалось) Сделал.
в ПТ запушил не законченное, думал в выходные дома доделаю.

2016-12-05 15:04 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/SupportedLanguages.java
> +    INVALID("", "", "", null, null);
Чего сразу INVALID, просто UNKNOWN) Но я не настаиваю :)

2016-12-05 15:05 UTC, meanmail approved these changes

2016-12-05 15:17 UTC, 2Pit commented on core/src/main/java/com/jetbrains/tmp/learning/SupportedLanguages.java
> +    INVALID("", "", "", null, null);
Мне кажется, что INVALID лучше, поскольку говорит, что мы не умеем работать с таким языком. Но в коде это почки не используется. Если найдем этому другое применение, то можно будет переименовать)

2016-12-06 11:40 UTC, merged