Download submission from list
StepicOrg/intellij-plugins pull request #48
Opened 2016-12-13 17:04 UTC by meanmail

- [ ] @taery 
- [ ] @2Pit 

[IDEA-90](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-90)
Теперь можно выбирать какое из решений загружать (выбор из двадцати последних решений).

![downloadsubmission](https://cloud.githubusercontent.com/assets/10301297/21149987/169fa7e0-c190-11e6-92ba-1359c0e8bd4f.png)

**Дополнительно:**
Выделены некоторые **Entities** из **StepikWrappers** (в будущем все сущности будут выделены и полностью соответвовать **Stepik API**).

2016-12-13 17:40 UTC, 2Pit commented
Думаю надо убрать id. Инфа полезная, но занимает слишком много места.


По возможности:
1. Показывать меню рядом с кнопкой "Download"
2. [Раскрасить стоки](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-90#u=1479420244371&viewimage=%25D0%2592%25D1%258B%25D0%25B4%25D0%25B5%25D0%25BB%25D0%25B5%25D0%25BD%25D0%25B8%25D0%25B5_014.png%3Ffile=87-6326&c=true&rw=506&rh=422&u=1479398633498)

2016-12-14 08:49 UTC, meanmail commented
Теперь подкрашивается фон
![downloadsubmission](https://cloud.githubusercontent.com/assets/10301297/21175431/d90074a2-c214-11e6-966b-b61940cc3bad.png)

2016-12-14 12:34 UTC, 2Pit commented
1. Поигрался с цветами, сделал более блеклыми
2. Выбранная строчка подсвечивается синим
3. передвинул отправку метрик в loadSubmission
Поскольку данная величина интереснее чем кол-во раз открытия меню
4. Число выводится в формате dd , чтобы текст был более выровненным
![_029](https://cloud.githubusercontent.com/assets/11159462/21182092/52d315f8-c212-11e6-83df-03e42a820205.png)

2016-12-14 12:36 UTC, taery commented
а это форматирование дат как-нибудь зависит от локали?

2016-12-14 12:37 UTC, taery commented
и как эта подстветка выглядит в раскраске а ля дракула?

2016-12-14 12:48 UTC, meanmail commented
Локаль и текущий часовой пояс учитывается, но порядок дата, месяц, год всегда такой, надо это учесть

2016-12-15 12:49 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/StepikConnectorGet.java
> +    public static SubmissionContainer getSubmissions(List<NameValuePair> nvps) {
А что за NameValuePair? Нельзя на стандартный джавовский Pair перейти?

2016-12-15 12:56 UTC, taery requested changes

2016-12-15 12:56 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/entities/Submission.java
> +    private String reply_url;
CamelCase?

2016-12-15 13:08 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/StepikConnectorGet.java
> +    public static SubmissionContainer getSubmissions(List<NameValuePair> nvps) {
Именно **NameValuePair** нужен, его требует HttpClient :)

2016-12-15 13:09 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/entities/Submission.java
> +    private String reply_url;
О! Спасибо, да

2016-12-15 13:10 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/stepik/StepikConnectorGet.java
> +    public static SubmissionContainer getSubmissions(List<NameValuePair> nvps) {
А, ок. Думала пережитки прошлого =)

2016-12-15 13:36 UTC, taery approved these changes

2016-12-16 10:36 UTC, merged