Show a progress when checking a step
StepicOrg/intellij-plugins pull request #62
Opened 2017-01-25 19:02 UTC by meanmail

**Who should approve:**
- [ ] @taery

**Solves issue(s):**
[IDEA-46](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-46)

**Description (and images):**
1. При проверке шага показывается фоновый прогресс бар.
![cheching_step](https://cloud.githubusercontent.com/assets/10301297/22304722/3515e412-e36b-11e6-907f-6a64e9a29d2c.png)

2. Рефакторинг класса StepikJavaPostAction: огромный метод разбил на несколько методов.

2017-01-25 22:44 UTC, 2Pit commented
3. Добавил отображение прогресса
![image](https://cloud.githubusercontent.com/assets/11159462/22312391/a5a5e4be-e368-11e6-8a0f-0424ea2e68e9.png)
4. Поток в котором проверяется решение теперь создаётся раньше т.е. время провисания UI уменьшено.

2017-01-26 04:12 UTC, meanmail commented
Подправил вычисление fraction прогресса, было неправильно.
Добавил текстовое отображение предполагаемого времени проверки + тесты.
Перенес некоторые методы в утилитный класс (они потом понадобятся для других actions).
Методы которые фактически являются static - сделал static.

2017-01-26 11:30 UTC, taery requested changes

2017-01-26 11:30 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/step/StepikJavaPostAction.java
> +        if (exception != null || submissions.isEmpty()) {
Кажется, я вижу копипаст. Выноси обработку в отдельные методы =) И лучше обрабатывать ошибку в try-catch, чем выносить в такие ифы.

2017-01-26 11:30 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/step/StepikJavaPostAction.java
> +        ActionUtils.notify(project, stepNode.getName() + " is " + stepStatus, hint, notificationType);
Возможно, тут лучше использовать какой-нибудь format стрингу (да и в других местах). Не с точки зрения производительности, а чтобы было понятно, где там нужно пробелы, где не нужно. Иначе можно случайно не написать и будет обидно

2017-01-26 11:30 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/step/ActionUtils.java
> +            result.append(seconds).append(" second").append(ending.apply(seconds)).append(" ");
вот тут например, не очень понятно, действительно ли тут везде нужные пробелы проставлены.

2017-01-26 17:30 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/actions/step/ActionUtils.java
> +    private static void appendTimePart(StringBuilder result, long value, String label) {
Еще кстати приватные/package_local(почему кстати не публичные просто) методы и переменные перемешаны. В целом, это не по конвенции джавы) у идеи вроде как есть галочка, которая умеет перераспределять методы и поля в нужном порядке

2017-01-26 17:34 UTC, taery approved these changes

2017-01-26 18:04 UTC, meanmail commented on stepik-union/src/main/java/org/stepik/plugin/actions/step/ActionUtils.java
> +    private static void appendTimePart(StringBuilder result, long value, String label) {
Рекомендуется использовать самый строгий уровень доступа везде, если нет веских причин поступать иначе:
>Use the most restrictive access level that makes sense for a particular member. Use private unless you have a good reason not to.

Из https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html
И в книгах об ООП вобщем и о Java в частности.

По поводу сортировки.
Переменные сортируются по модификатору доступа. А вот методы нет, по функциональности. Но вроде IDEA по-умолчанию так и сортирует.

http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141855.html#1852 (там в конце табличка)

2017-01-26 18:07 UTC, merged