Feature/small changes
StepicOrg/intellij-plugins pull request #66
Opened 2017-01-31 15:47 UTC by 2Pit

- [ ]  @taery 
- [ ]  @meanmail  

Маленькие изменения.

1. Исправлена версия плагина 
2. Исправлено отображение проверки заданий
Теперь таймер не переписывает имя потока.

![image](https://cloud.githubusercontent.com/assets/11159462/22471522/a0396cec-e7e3-11e6-89b5-9114d8c2d75e.png)

3. Выключил подсказки к управляющим комментариям
На мой взгляд они только мешают. И они плохи тем, что отличаются только одним словом.

без подсказок:
![image](https://cloud.githubusercontent.com/assets/11159462/22471602/ea01a02e-e7e3-11e6-92c6-72ba89e54096.png)

с подсказками:
![image](https://cloud.githubusercontent.com/assets/11159462/22471992/4765f6ec-e7e5-11e6-84b3-65592500353c.png)

2017-01-31 16:00 UTC, taery requested changes

2017-01-31 16:00 UTC, taery commented on stepik-union/src/main/java/org/stepik/plugin/utils/DirectivesUtils.java
> +    private static final String START_HINT = "Please note, only the code BELOW will be sent to Stepik";
@2Pit я бы не меняла Stepik.org просто на Stepik

2017-01-31 21:32 UTC, meanmail requested changes

2017-01-31 21:32 UTC, meanmail commented on gradle.properties
> +pluginVersion=0.10
Версию меняем после code freeze в ветке **release/\*** (не в ветке develop)

2017-01-31 21:33 UTC, meanmail commented
> Теперь таймер не переписывает имя потока.

Мне кажется наоборот плюс, что переписывает. Пользователь без открытия окошка фонового процесса увидит оставшиеся время. Имя потока (да и время) видно только, если поток один. Иначе всё равно ничего кроме лишь, например, "2 processing running..." не видно.

2017-01-31 21:35 UTC, 2Pit commented on gradle.properties
> +pluginVersion=0.10
Ок

2017-01-31 21:48 UTC, 2Pit commented
Если по старому, то в случае одного процесса, после появления таймера становится не понятно какая вообще задача решается 
"Checking Step: step6" затирается на "Ends in 2 seconds".

В случае двух процессов. Их имена не отображаются в свернутом варианте, поэтому преимуществ не вижу. А в развернутом сохраняется инфа о том какие степы проверяются.

Я считаю, что имена степов важнее чем таймер. Если проверка пойдет на минуты пользователь может забыть, что он отправлял. Или начать сомневаться и думать, что он отправил не то.

2017-01-31 21:51 UTC, 2Pit commented
Можно имя степа задать через setText2(), но это странно)

2017-02-01 11:19 UTC, taery approved these changes

2017-02-01 12:11 UTC, meanmail approved these changes

2017-02-01 12:12 UTC, merged