Added support single line string quiz
StepicOrg/intellij-plugins pull request #78
Opened 2017-02-20 16:54 UTC by meanmail

**Who should approve:**
- [ ] @taery

**Solves issue(s):**
[IDEA-178](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-178)
**Description (and images):**
Поддержка текстовых задач (одна строка).
![string_quiz_active](https://cloud.githubusercontent.com/assets/10301297/23130582/9a2c6058-f7b9-11e6-8158-419d510cf9f8.png)
![string_quiz_wrong](https://cloud.githubusercontent.com/assets/10301297/23130586/9f074c50-f7b9-11e6-861c-58a9e12d5ab9.png)
![string_quiz_solved](https://cloud.githubusercontent.com/assets/10301297/23130593/a2a34c4c-f7b9-11e6-9ff0-44e2ea2d77c5.png)

2017-02-20 17:12 UTC, meanmail commented
![string_quiz_solved](https://cloud.githubusercontent.com/assets/10301297/23135247/6b532058-f7ca-11e6-8e5b-56153fc65312.png)

2017-02-20 22:15 UTC, meanmail commented
![restrictions](https://cloud.githubusercontent.com/assets/10301297/23143556/a894b6a0-f7f4-11e6-97f3-041443b8d5c6.png)

2017-02-21 11:47 UTC, taery requested changes

2017-02-21 11:47 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +    private boolean loadAttempt(@NotNull StepikApiClient stepikApiClient, long userId) {
Мне кажется, уже точно стоит смотреть как минимум на флаг `has_submissions_restrictions` у шага и если  он включен, то на количество оставшихся попыток `max_submissions_count`. Если попытки кончились, бекенд не вернет attempt (детали про это [тут](https://vyahhi.myjetbrains.com/youtrack/issue/EDY-5546))

2017-02-21 11:47 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +    private boolean loadAttempt(@NotNull StepikApiClient stepikApiClient, long userId) {
Хотя может и в отдельную задачу это лучше.

2017-02-21 11:47 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +    private boolean loadAttempt(@NotNull StepikApiClient stepikApiClient, long userId) {
Про экзамены, у секций есть флаг `is_exam`. При его наличии лучше не загружать такую секцию и точно не делать самим аттемптов.

2017-02-21 11:47 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +    Dataset getDataset() {
Я запуталась. Это String или dataset квиз?

2017-02-21 11:47 UTC, taery commented on core/src/main/resources/code-mirror/codemirror.css
> +    margin: 10px 20px;
мб по 20 с обоих сторон?

2017-02-21 11:47 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +                status = "empty";
а нельзя вот [тут](https://github.com/StepicOrg/intellij-plugins/pull/78/files?diff=unified#diff-9fe81efef76e1f5c9de1e3113b6efd3dR27) возвращать сразу "empty" и не делать потом таких проверок?

2017-02-21 12:14 UTC, meanmail commented on core/src/main/resources/code-mirror/codemirror.css
> +    margin: 10px 20px;
Такой синтаксис: `margin: <top & bottom> <left&right>`
По бокам 20px, сверху и снизу по 10px

2017-02-21 12:14 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +    Dataset getDataset() {
Это dataset квиз

2017-02-21 12:14 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +                status = "empty";
Думаю нельзя, так как api должен возвращать значение как есть. Здесь нужно "empty", а в другом месте нет.

2017-02-21 12:14 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +    private boolean loadAttempt(@NotNull StepikApiClient stepikApiClient, long userId) {
Я то тестировал на тестовом курсе, а у меня там конечно аттемпты отдаются и после превышения лимита. Сделаю в этот PR.

2017-02-21 12:18 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +                status = "empty";
а зачем тут нужно empty? лучше единообразно

2017-02-21 12:19 UTC, taery commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +    Dataset getDataset() {
Если это датасет, то учитываются ли тут таймлимиты? (задача вроде не про датасет)

2017-02-21 12:21 UTC, taery commented on core/src/main/resources/code-mirror/codemirror.css
> +    margin: 10px 20px;
А, да, я туплю. Пардон

2017-02-21 12:29 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +    Dataset getDataset() {
Теперь я туплю, нет это не dataset quiz, это поле у attempt

2017-02-21 12:31 UTC, meanmail commented on core/src/main/java/com/jetbrains/tmp/learning/courseFormat/StepHelper.java
> +                status = "empty";
Согласен, тут не нужно empty

2017-02-22 09:53 UTC, meanmail commented
Теперь, когда попытки закончились, кнопка "Решить снова" не показывается, аттемпты не создаются (даже для staff).
![attempt1](https://cloud.githubusercontent.com/assets/10301297/23206194/54a5f6cc-f91f-11e6-953f-2908b1130fa0.png)
![attempt2](https://cloud.githubusercontent.com/assets/10301297/23206200/57de8872-f91f-11e6-9ae1-f345c107f89a.png)
![attempt3](https://cloud.githubusercontent.com/assets/10301297/23206206/5bb70a00-f91f-11e6-820d-bdd151ee0ebf.png)

2017-03-07 06:36 UTC, merged