Support a debug level
StepicOrg/intellij-plugins pull request #79
Opened 2017-02-20 21:12 UTC by 2Pit

- [ ]  @taery 
- [ ]  @meanmail 

[IDEA-188](https://vyahhi.myjetbrains.com/youtrack/issue/IDEA-188)
Теперь при запуске плагина в песочнице файл конфигурации перезаписывается файлом
`buildSrc/src/resources/log.xml`.

Различия со стандартными конфигурациями https://github.com/StepicOrg/intellij-plugins/commit/f50091665c06ff6c56f21cfe58de83d6664cb043

К сожалению, использование агрумента jvm
`-Dlog4j.configuration=file:${path_to_file}/log.xml`
не помогает, поэтому и решил перезаписывать файл.

log.xml в IDEA, CLion и PyCharm - одинаковый.

![image](https://cloud.githubusercontent.com/assets/11159462/23141911/22b52efe-f7ca-11e6-8a1b-758aca1b2a54.png)

2017-02-21 10:16 UTC, meanmail requested changes

2017-02-21 10:16 UTC, meanmail commented on buildSrc/src/main/groovy/org/stepik/gradle/plugins/jetbrains/BaseRunTask.groovy
> +    private void configureLogProperties() {
Только не в этом классе. Перенеси это в PrepareSandboxTask строка 107 после вызова disableIdeUpdate().
Просто у Gradle хитрая система, он следит за входными и выходными параметрами задачи (в том числе и за состоянием файлов) и если, что-то менять не в той задаче, то он может задачу пропустить, посчитав, что раз входные параметры не изменились, то и нет смысла выполнять задачу вообще. У нас и так с этим проблема, поэтому приходиться постоянно делать clean.

2017-02-21 12:31 UTC, taery commented
@2Pit, @meanmail, пишите пожалуйста побольше описания в задачах зачем это нужно (одного заголовка мне недостаточно). 

А то я по описанию задачи совсем не могу понять ее суть =)

2017-02-21 12:32 UTC, taery commented on buildSrc/src/main/groovy/org/stepik/gradle/plugins/jetbrains/BaseRunTask.groovy
> +        if (logURL == null){
И `CTRL+ALT+L` пробелов не хватает между ) и { 😄

2017-02-22 16:41 UTC, 2Pit commented
Подправил описание тут и в YT )

2017-02-27 15:01 UTC, meanmail commented
Очень плохо, что заменяется файл в кэше gradle. По хорошему все файлы расположенные там должны быть Read Only.
Надо бы разобраться как именно IDEA конфигурирует log4j. Но это она точно не делает через переменные окружения.

2017-03-07 10:59 UTC, 2Pit commented
Кажется нашёл. 
idea-sandbox/config/options/options.xml
``` 
<application>
  <component name="PropertiesComponent">
    <property name="log.debug.categories" value="#com.jetbrains.tmp" />
  </component>
</application>
```

Эту же настройку можно задавать через UI.
`Help | Debug log settings` << LoggerName f.e. "#com.jetbrains.tmp"

2017-03-07 13:34 UTC, closed without merging