Implemented Auto run Reformat code
StepicOrg/intellij-plugins pull request #9
Opened 2016-10-15 12:44 UTC by meanmail

- [ ] @taery 
- [ ] @2Pit 

Реализован автоформат кода, после добавления/уборки окружающего кода.
В этом PR решается только эта задача #8 .

2016-10-15 13:00 UTC, taery requested changes

2016-10-15 13:00 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +import com.intellij.openapi.actionSystem.*;
Лучше со звездочкой импортировать, только когда *очень* много импортов. (100+ можно в настройках идеи поставить)

2016-10-15 13:00 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +            ans[i + 1] = text[i];
Может тогда уже копировать не в цикле? Какой-нибудь System.arrayCopy()?

2016-10-15 13:00 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    private static class ActionDataContext implements DataContext {
Лучше не делать вложенных классов, почему именно так? Может можно просто в отдельный класс обычный вынести?

2016-10-15 13:00 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        AnActionEvent event = new AnActionEvent(null, dataContext, ActionPlaces.UNKNOWN, presentation, actionManager, 0);
а этот реформат как живьем выглядит? оно просто реформатирует, без показа доп окошек? оно учитывает optimise imports?

2016-10-15 13:02 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +import com.intellij.openapi.actionSystem.*;
Проглядел, идея постаралась :)

2016-10-15 13:03 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +            ans[i + 1] = text[i];
В следующем PR эта часть будет реализована по-другому. Не хотел смешивать задачи.

2016-10-15 13:03 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +            ans[i + 1] = text[i];
ok

2016-10-15 13:05 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        AnActionEvent event = new AnActionEvent(null, dataContext, ActionPlaces.UNKNOWN, presentation, actionManager, 0);
Делает тоже самое, что и нажатие в меню Code -> Reformat Code. Там кажется зависит от настроек. Всё таки надо добавить гифку.

2016-10-15 13:07 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        AnActionEvent event = new AnActionEvent(null, dataContext, ActionPlaces.UNKNOWN, presentation, actionManager, 0);
Мне кажется, что нужно, чтобы не зависело от настроек. Нужно делать реформат всегда, вместе с импортами. Думаю можно попробовать просто вытащить нужный кусок кода из action-а, а не запускать прямо весь. Иначе будет очень неудобно этим пользоваться.

2016-10-15 13:08 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    private static class ActionDataContext implements DataContext {
Одноразовый класс. Даже не знаю где он ещё пригодится. Не стал делать анонимным так как нужен конструктор.

2016-10-15 13:10 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +    private static class ActionDataContext implements DataContext {
Как минимум его не стоит делать где-то в середине. Приватные лучше уносить в конец, наверное.

2016-10-15 13:57 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        AnActionEvent event = new AnActionEvent(null, dataContext, ActionPlaces.UNKNOWN, presentation, actionManager, 0);
![autoformat](https://cloud.githubusercontent.com/assets/10301297/19410571/e046cbaa-9319-11e6-9b96-394e3b267933.gif)

2016-10-15 13:59 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        AnActionEvent event = new AnActionEvent(null, dataContext, ActionPlaces.UNKNOWN, presentation, actionManager, 0);
ага, вижу. надо чтобы импорты тоже автоматом.

2016-10-15 14:10 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        AnActionEvent event = new AnActionEvent(null, dataContext, ActionPlaces.UNKNOWN, presentation, actionManager, 0);
Автоматически добавлялись импорты?

2016-10-15 14:13 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        AnActionEvent event = new AnActionEvent(null, dataContext, ActionPlaces.UNKNOWN, presentation, actionManager, 0);
ага. Хотя я вот тут подумала. В этом случае они ведь и не добавятся автоматом =( Ладно, пусть пока так будет, это уже лучше чем с табами. А про импорты нужно думать.

2016-10-15 14:56 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/DirectivesUtils.java
> +        AnActionEvent event = new AnActionEvent(null, dataContext, ActionPlaces.UNKNOWN, presentation, actionManager, 0);
Автоматом добавляются только импорты, которые однозначно понятно из какого пакета брать. Например, IOException добавиться, а вот InputStream - нет.

2016-10-17 15:12 UTC, 2Pit commented
Всё ок. Только хочется убрать автомачическое форматирование при удалении директив. Оно показывает себя не с лучшей стороны.
![image](https://cloud.githubusercontent.com/assets/11159462/19443347/1e8ed494-9495-11e6-86ef-2961f1c72b51.png)

2016-10-17 15:28 UTC, taery commented
@2Pit, а что ты предлагаешь делать при удалении, табы?

2016-10-17 16:04 UTC, 2Pit commented
Ничего не делать. Да, скорее всего будут лишние табы, но это лучше чем текущее поведение)

2016-10-17 16:05 UTC, taery commented
ok

2016-10-17 16:50 UTC, meanmail commented
Сделал автоформат только после добавления директив.

2016-10-17 17:58 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/InsertStepikDirectives.java
> +            ReformatWholeEditor.processCode(project);
Название еще кажется очень странным. Может просто `ReformatUtils`? это же вроде как утилиты со статическими методами.

2016-10-17 18:00 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/ReformatWholeEditor.java
> +        else {
И давайте все же не будем делать else на новой строке, я каждый раз смотрю и плачу.

2016-10-17 18:03 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/ReformatWholeEditor.java
> +        myProcessor = mixWithReformatProcessor(myProcessor, file);
а зачем это в отдельном методе?

2016-10-17 18:05 UTC, taery commented on stepik-union/src/org/stepik/plugin/actions/ReformatWholeEditor.java
> +        myProcessor = mixWithReformatProcessor(myProcessor, file);
Я бы предложила тут написать:
```
AbstractLayoutCodeProcessor processor = new ReformatCodeProcessor(new OptimizeImportsProcessor(project, file), false)
```
и не усложнять себе жизнь =)

2016-10-17 18:34 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/ReformatWholeEditor.java
> +        myProcessor = mixWithReformatProcessor(myProcessor, file);
Можно ещё проще =)
`new ReformatCodeProcessor(new OptimizeImportsProcessor(project, file), false).run();`

2016-10-17 18:35 UTC, meanmail commented on stepik-union/src/org/stepik/plugin/actions/ReformatWholeEditor.java
> +        else {
Я и сам чуть не заплакал, ох уж эта не внимательность, обещаю так не делать :)

2016-10-17 20:19 UTC, taery approved these changes

2016-10-17 20:20 UTC, taery commented
@2Pit, от меня ОК, если все нравится - ставь галочку и мержи.

2016-10-18 09:15 UTC, merged